# Generated by Django 6.0.4 on 2026-05-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_location',
            field=models.CharField(blank=True, help_text='Location specified by the patient', max_length=255, null=True),
        ),
    ]
