# Generated by Django 6.0.4 on 2026-05-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_date_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid in INR', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, help_text='Razorpay Order ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, help_text='Razorpay Payment ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='razorpay_signature',
            field=models.CharField(blank=True, help_text='Razorpay Signature', max_length=255, null=True),
        ),
    ]
