# Generated by Django 4.2.30 on 2026-05-22 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_auditlog_timestamp'),
        ('appointments', '0004_appointment_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='check_in_time',
            field=models.DateTimeField(blank=True, help_text='Timestamp when checked in', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='delay_offset',
            field=models.IntegerField(default=0, help_text='Delay offset in minutes'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='priority',
            field=models.IntegerField(default=3, help_text='1: Emergency, 2: Walk-in, 3: Regular'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='queue_token',
            field=models.CharField(blank=True, help_text='Queue Token, e.g. T-102', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='queue_type',
            field=models.CharField(default='scheduled', help_text='scheduled | walkin | emergency', max_length=20),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=20, unique=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('PAID', 'PAID'), ('PENDING', 'PENDING'), ('FAILED', 'FAILED')], default='PENDING', max_length=20)),
                ('payment_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('date_generated', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='users.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='users.patient')),
            ],
        ),
    ]
