# Generated by Django 6.0.4 on 2026-05-25 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_check_in_time_appointment_delay_offset_and_more'),
        ('users', '0005_doctor_average_rating_doctor_total_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('missed', 'Missed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ConsultationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_rating', models.IntegerField(default=0)),
                ('doctor_rating', models.IntegerField(default=0)),
                ('receptionist_rating', models.IntegerField(default=0)),
                ('technician_rating', models.IntegerField(default=0)),
                ('hospital_rating', models.IntegerField(default=0)),
                ('consultation_comments', models.TextField(blank=True, null=True)),
                ('doctor_comments', models.TextField(blank=True, null=True)),
                ('receptionist_comments', models.TextField(blank=True, null=True)),
                ('technician_comments', models.TextField(blank=True, null=True)),
                ('hospital_comments', models.TextField(blank=True, null=True)),
                ('general_comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.patient')),
            ],
            options={
                'verbose_name_plural': 'Consultation Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
