# Generated by Django 6.0.4 on 2026-05-28 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_appointment_status_consultationreview'),
        ('users', '0005_doctor_average_rating_doctor_total_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_referrals', to='users.patient')),
                ('referred_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to='users.doctor')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_sent', to='users.doctor')),
            ],
            options={
                'verbose_name_plural': 'Specialist Referrals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorCalendarOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('leave', 'On Leave'), ('hold', 'On Hold'), ('unavailable', 'Unavailable')], max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('sessions', models.JSONField(blank=True, help_text='Custom available session times', null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_overrides', to='users.doctor')),
            ],
            options={
                'verbose_name_plural': 'Doctor Calendar Overrides',
                'unique_together': {('doctor', 'date')},
            },
        ),
    ]
