# Generated by Django 6.0.4 on 2026-04-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('senior_doctor', 'Senior Doctor'), ('doctor', 'Doctor'), ('receptionist', 'Receptionist'), ('technician', 'Technician'), ('patient', 'Patient')], max_length=20),
        ),
    ]
