# Generated by Django 6.0.4 on 2026-05-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_auditlog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average consultation rating', max_digits=3),
        ),
        migrations.AddField(
            model_name='doctor',
            name='total_reviews',
            field=models.IntegerField(default=0, help_text='Total number of consultation reviews'),
        ),
    ]
