# Generated by Django 4.2.30 on 2026-05-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='dosage_form',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='side_effects',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='substitutes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='use_case',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='drug',
            table='drugs',
        ),
    ]
