# Generated by Django 4.2.30 on 2026-05-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0002_drug_dosage_form_drug_manufacturer_drug_side_effects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='findings',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='scan_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='status',
            field=models.CharField(blank=True, default='completed', max_length=50, null=True),
        ),
    ]
