# Generated by Django 6.0.4 on 2026-05-14 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0003_scanresult_findings_scanresult_scan_date_and_more'),
        ('users', '0003_doctoruser_patientuser_receptionistuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_orders', to='users.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_orders', to='users.patient')),
            ],
        ),
    ]
