# Generated by Django 4.2.30 on 2026-05-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0005_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='scan_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
