# Generated by Django 6.0.4 on 2026-05-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0006_alter_chatmessage_sent_at_alter_scanresult_scan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
